{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": ">   ???\nE   assert 1 == 2\n\nE:\\test_AutoTest\\testcases\\test_one.py:20: AssertionError"}, "attachments": [{"name": "log", "source": "40346a62-114d-4d94-8233-b82003403994-attachment.txt", "type": "text/plain"}], "start": 1687702440505, "stop": 1687702440505, "uuid": "e43a19a1-0c86-4670-9e62-e4d38408068c", "historyId": "8641333e0f78a2c14426c7a681c23115", "testCaseId": "8641333e0f78a2c14426c7a681c23115", "fullName": "testcase.test_one#test_two", "labels": [{"name": "tag", "value": "test"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_one"}, {"name": "host", "value": "DESKTOP-SR3HJK4"}, {"name": "thread", "value": "3488-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_one"}]}