{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <testcase.test_three.TestThree object at 0x000001D6FB53B310>\n\n>   ???\nE   assert 1 == 2\n\nE:\\test_AutoTest\\testcases\\test_three.py:19: AssertionError"}, "attachments": [{"name": "log", "source": "076c6d48-3035-465d-8663-6eed122637b9-attachment.txt", "type": "text/plain"}], "start": 1687702440589, "stop": 1687702440589, "uuid": "b04d58b9-3789-461f-9b99-175c6ea9907d", "historyId": "ad7a339c51768cc5581ce811cbd27794", "testCaseId": "ad7a339c51768cc5581ce811cbd27794", "fullName": "testcase.test_three.TestThree#test_two", "labels": [{"name": "tag", "value": "pro"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_three"}, {"name": "subSuite", "value": "TestThree"}, {"name": "host", "value": "DESKTOP-SR3HJK4"}, {"name": "thread", "value": "3488-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_three"}]}